### ISSUE TITLE
wasavi and httpie

### ISSUE THREAD

**Issue by idvorkin** [pixelastic/oroshi#3]
Going through your dot files I found a treasure trove of good stuff. Only thing I didn't see where wasavi and httpie, if you know 'em cool.  Else, check 'em out.

**Comment by pixelastic** [comment]
Oh thanks!

I didn't know about wasavi, that looks pretty useful, I'll give it a try!

I used httpie a few times, it always looked pretty nice, but it never actually made it to my regular toolbelt. I guess I don't do that much HTTP calls from the terminal.

Glad this could help you somehow. I always find good stuff by looking into others dotfiles as well :)
